version: "3"
services:
  api:
    build: 
      context: ./api-node
      dockerfile: Dockerfile.prod
    ports:
     - "80:8123"
    environment:
     - DATABASE_HOST=changeit
     - DATABASE_NAME=changeit
     - DATABASE_USER=changeit
     - DATABASE_PASS=changeit
    volumes:
     - './api-node/api:/app'