version: "3"
services:
  api:
    build: 
      context: ./api-node
      dockerfile: Dockerfile.dev # change to Dockerfile.prod
    ports:
     - "8123:8123"
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
     - DATABASE_NAME=LOGSKILLS
     - DATABASE_USER=logskills_user
     - DATABASE_PASS=123
     
    volumes:
     - './api-node/api:/app'
  db:
    build: ./database-service
    command: --lower_case_table_names=1
    command: --default-authentication-plugin=mysql_native_password
    restart: always